# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gloria # your blog title name
subtitle: 
author: GaoGe # ä½œè€…
language: 
timezone: 

# custom Site settings
# more detail check out docs
SEOTitle: Gloria's blog 
email: gaoge21@outlook.com
description: ğ™ğ™–ğ™«ğ™š ğ™– ğ™£ğ™ğ™˜ğ™š ğ™™ğ™–ğ™® á
keyword: # seo key words

favicon: # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://haojen.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# SNS settings
# RSS:
weibo_username: 
zhihu_username: pigeon1021
github_username: GaoGe21
twitter_username: 
facebook_username:  
linkedin_username: 

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: 

# Duoshuo settings
duoshuo_username:  # ä½ çš„å¤šè¯´å¸å·
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Use livere
use_livere:

# Valine comment system https://valine.js.org
valine: 
  enable: false
  appid:  #Leancloudåº”ç”¨çš„appId
  appkey:  #Leancloudåº”ç”¨çš„appKey
  verify: false #éªŒè¯ç 
  notify: false #è¯„è®ºå›å¤æé†’
  avatar: mm #è¯„è®ºåˆ—è¡¨é»˜è®¤å¤´åƒæ ·å¼
  placeholder: Just go go #è¯„è®ºæ¡†å ä½ç¬¦

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar: true
sidebar-about-description: "ğ™ğ™–ğ™«ğ™š ğ™– ğ™£ğ™ğ™˜ğ™š ğ™™ğ™–ğ™® á"
sidebar-avatar: https://s3.ax1x.com/2021/01/17/ss45lQ.jpg


# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# friends
friends:  # å‹é“¾

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/GaoGe21/xpigeon.github.io
  branch: 


# img CDN path
cdn-url:  # ä½ çš„CDNåœ°å€

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: #åšæ–‡é»˜è®¤çš„å›¾ç‰‡
post-default-img-mobile: #ç§»åŠ¨ç«¯æ˜¾ç¤ºçš„å›¾ç‰‡

# search api , set your custom key
swiftype_key: 


# archive page title 
archive:
    title: archives
    description: å¯ä»¥æ ¹æ®å½’æ¡£æ—¥æœŸæ£€ç´¢æ‰€æœ‰æ–‡ä»¶

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
     use: live2d-widget-model-hijiki
  display:
    position: right
    width: 150
    height: 150
  mobile:
    show: true